### ISSUE TITLE
refactor: else문을 사용하지 않도록 로직 수정

### ISSUE THREAD

**Issue by Jeongjjuna** [DevtoonProject/crazy-cookie#35]
## ✨ 설명
- [ ]  else문을 사용하지 않도록 로직 수정

## 💡️ 이슈
- else문을 사용하면 분기점이 많아지면서 검증 조건에 대한 복잡도가 증가할 수 있다고 생각합니다. 이로 인해  실수를 유발할 수 있기때문에 가능하다면 else문을 사용하지 않도록 수정해보면 좋을 것 같습니다.

**Comment by youjungHwang** [comment]
해당 이슈는 다음 브랜치에서 같이 해결했습니다.
- #52
