### ISSUE TITLE
refactor: 부정형 조건문 제거

### ISSUE THREAD

**Issue by Jeongjjuna** [DevtoonProject/crazy-cookie#36]
## ✨ 설명
- [ ] 부정형 조건문을 제거

## 💡️ 이슈
- 코드에 부정형보다는 긍정형으로 바꿔서 이해하기 쉽도록 하면 좋을 것 같습니다. 또한 Optional을 활용하여 가독성 있게 Exception을 던질 수 도 있을 것 같습니다.
<img width="415" alt="image" src="https://github.com/FreakPeople/freak-devtoon/assets/87998104/902bfc3a-8e64-4385-b0ee-bf57019f274a">

**Comment by youjungHwang** [comment]
해당 이슈는 다음 브랜치에서 같이 해결했습니다.
- #49
