### ISSUE TITLE
refactor: else문을 사용하지 않도록 변경

### ISSUE THREAD

**Issue by Jeongjjuna** [DevtoonProject/crazy-cookie#40]
## ✨ 설명
- [ ] else문을 사용하지 않도록 변경

## 💡️ 이슈
- Policy의 타입이 많아지면 else if 조건문도 연달아 많아지기 때문에, else문을 제거할 수 있도록 로직을 변경하면 좋을 것 같습니다.

<img width="546" alt="image" src="https://github.com/FreakPeople/freak-devtoon/assets/87998104/c6b9fe17-3934-4320-8a63-036abd3c986b">

**Comment by youjungHwang** [comment]
해당 이슈는 다음 브랜치에서 같이 해결했습니다.
- #52
