### ISSUE TITLE
refactor: enum타입의 policy type을 활용하여 switch문 제거

### ISSUE THREAD

**Issue by Jeongjjuna** [DevtoonProject/crazy-cookie#43]
## ✨ 설명
- [ ] enum타입의 policy type을 활용하여 switch문 제거

## 💡️ 이슈
- Policy 타입에 대하여 string 문자열을 그대로 사용하고 있는데, Enum으로 상수화 시키면 가독성 및 객체지향 프로그래밍에 도움이 될 것 같습니다.
- 기존에 PolicyFactory객체의 switch로직을 활용하여 정책을 생성하던 방식에서 Enum을 활용하여 객체지향적으로 생성할 수 있도록 변경하면 좋을 것 같습니다.

**Comment by youjungHwang** [comment]
해당 이슈는 다음 브랜치에서 같이 해결했습니다.
- #52
